using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CircleController : MonoBehaviour
{
       float speed = 200f;

       float jumpSpeed = 400f;

    // Start is called before the first frame update
    void Start()
       {

       }

    // Update is called once per frame
    void Update()
       {
          Rigidbody2D rb = GetComponent<Rigidbody2D>();


             //Is player pressing D Key
          if (Input.GetKey(KeyCode.D))
             {
                rb.AddForce(Vector2.right * speed * Time.deltaTime);
             }
          
          else if (Input.GetKey(KeyCode.A))
             {
                rb.AddForce(Vector2.left * speed * Time.deltaTime);
             }
          
          else
             {
                rb.velocity = new Vector2(0, rb.velocity.y);
             }


          if (Input.GetKeyDown(KeyCode.Space))
             {
                rb.AddForce(Vector2.up * jumpSpeed);
             }
       }
}
